/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define FULLY_CONNECTED_MVE_1_OUT_CH 4
#define FULLY_CONNECTED_MVE_1_IN_CH 20
#define FULLY_CONNECTED_MVE_1_INPUT_W 1
#define FULLY_CONNECTED_MVE_1_INPUT_H 1
#define FULLY_CONNECTED_MVE_1_DST_SIZE 4
#define FULLY_CONNECTED_MVE_1_INPUT_SIZE 20
#define FULLY_CONNECTED_MVE_1_OUT_ACTIVATION_MIN -128
#define FULLY_CONNECTED_MVE_1_OUT_ACTIVATION_MAX 127
#define FULLY_CONNECTED_MVE_1_INPUT_BATCHES 1
#define FULLY_CONNECTED_MVE_1_INPUT_OFFSET 128
#define FULLY_CONNECTED_MVE_1_OUTPUT_OFFSET -41
#define FULLY_CONNECTED_MVE_1_OUTPUT_MULTIPLIER 1689282354
#define FULLY_CONNECTED_MVE_1_OUTPUT_SHIFT -8
#define FULLY_CONNECTED_MVE_1_ACCUMULATION_DEPTH 20
