// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_mve_1_input[20] = {32, 47,   -94, -91, -88, 29,  -126, -6, 69,  -97,
                                              71, -127, -91, 19,  -74, -50, -49,  86, -42, 110};
