/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_mve_1_weights[80] = {
    72,  -102, 21, 66,   94,  81,  -24, -71, -9,  -35, 54,  72,  -3,  46,  -43, -32, -76, -82, 19,  70,
    -25, 104,  19, 35,   26,  37,  -34, 82,  -38, -10, 82,  33,  -97, 31,  -60, 123, -89, -31, -69, -104,
    -94, -121, 80, -58,  116, 95,  13,  45,  -29, -22, -55, 71,  -36, -1,  -84, 116, -70, -99, 110, 109,
    -74, 63,   31, -127, -65, -70, 36,  37,  -64, -70, 34,  114, -16, -66, -22, 44,  -17, 53,  -32, 59};
