/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_4_input[40] = {-32,  96, -96, -96,  64, -112, -48, 96,  0,  -48,  -64, -32, 48,  -80,
                                       32,   96, -96, -112, 0,  -48,  -48, 16,  96, -48,  96,  -32, -16, -80,
                                       -112, 48, -16, 48,   16, 16,   32,  -64, 64, -112, -48, -80};
