// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_4_input[40] = {-49, 31, 94,  36,   -124, -57, -39, -54, 70,   -37, -127, -36, 43,   94,
                                       43,  13, -73, -14,  -16,  -48, 3,   -47, -109, -72, 43,   -53, -128, 118,
                                       -65, 60, 8,   -112, 87,   119, -95, 26,  95,   -74, 24,   10};
