// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_null_bias_0_input[40] = {
    -97,  -113, 118, 69, 39,   -32, -1,   -79, -30, -8, 46,   -13, 82,  -19, 15, 105, 94,  -56, 35, 55,
    -122, -105, 70,  33, -128, -87, -109, 50,  2,   78, -113, 113, -50, -33, 19, -6,  -38, 122, 18, -121};
