// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_null_bias_0_output_ref[40] = {1,  -91, 52, -57,  65,  -99, 62, 59,   55, -110, 97,  -2,  -15, -128,
                                                   85, 36,  38, -128, -13, -56, 49, -107, 29, 62,   -26, -96, 29,  -128,
                                                   3,  -16, 41, -13,  14,  -54, 22, -96,  17, -17,  13,  -15};
