/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_kernel_3x3_input[100] = {
    -103, 50,  -17, -59,  85,   87,  -75,  61,   56,   25,   -110, 50,  121, 111, -65,  84,  -102, -32, -111, 120,
    53,   56,  -12, -21,  111,  4,   -93,  -110, 78,   -57,  -18,  -99, -22, 114, -39,  97,  -40,  -50, -128, -54,
    2,    -58, 16,  37,   -104, -10, -119, 54,   -128, -93,  -6,   7,   10,  115, -124, -87, 125,  15,  -84,  -128,
    107,  5,   101, -101, 35,   -55, -26,  28,   110,  -105, 25,   21,  105, -58, -118, -84, -94,  75,  -112, -55,
    -32,  63,  -98, 19,   102,  11,  5,    60,   -89,  56,   82,   62,  107, -89, -113, 59,  -110, -26, 15,   5};
