// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_kernel_3x3_output_mult[5] = {1568114264, 1660356338, 1528581989, 1370452890, 1449517439};
