// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_kernel_3x3_output_ref[30] = {-14, -59, -34,  21,  18, -5, -29, -91, 8, 27, 35, -87, -103, -4,  32,
                                                  50,  -36, -104, -42, 16, 48, -61, -8,  9, 10, 65, -76, -59,  -16, 30};
