/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_kernel_3x3_weights[45] = {117, -127, -62, -121, 22,  113, -37, 112,  71,  -96, 102, 119,
                                               -4,  64,   -16, 88,   -32, -72, 12,  -115, 63,  36,  12,  51,
                                               33,  -127, -61, 115,  -33, -22, -49, -9,   -35, 64,  23,  -22,
                                               118, -127, -49, -127, -33, -85, -55, 127,  125};
