// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_kernel_3x3_weights[45] = {117, -127, -62, -121, 22,  113, -37, 112,  71,  -96, 102, 119,
                                               -4,  64,   -16, 88,   -32, -72, 12,  -115, 63,  36,  12,  51,
                                               33,  -127, -61, 115,  -33, -22, -49, -9,   -35, 64,  23,  -22,
                                               118, -127, -49, -127, -33, -85, -55, 127,  125};
