// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#define CONV_5_OUT_CH 1
#define CONV_5_IN_CH 128
#define CONV_5_INPUT_W 128
#define CONV_5_INPUT_H 1
#define CONV_5_DST_SIZE 32
#define CONV_5_INPUT_SIZE 16384
#define CONV_5_OUT_ACTIVATION_MIN -88
#define CONV_5_OUT_ACTIVATION_MAX 127
#define CONV_5_INPUT_BATCHES 1
#define CONV_5_FILTER_X 3
#define CONV_5_FILTER_Y 3
#define CONV_5_STRIDE_X 4
#define CONV_5_STRIDE_Y 4
#define CONV_5_PAD_X 0
#define CONV_5_PAD_Y 1
#define CONV_5_OUTPUT_W 32
#define CONV_5_OUTPUT_H 1
#define CONV_5_INPUT_OFFSET 128
#define CONV_5_OUTPUT_OFFSET 127
#define CONV_5_DILATION_X 1
#define CONV_5_DILATION_Y 1
