// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_5_output_ref[32] = {-88, -6,  -88, -88, -88, 127, -88, -88, 127, -88, -88, 127, -88, 127, -88, -88,
                                    127, 127, -88, 127, 127, -88, -88, -88, 4,   127, 127, -88, -88, -88, -88, 127};
