// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t svdf_2_weights_time[20] = {-31, -88, -10, -72, -119, -6, -70, 63,  -10, 93,
                                       5,   42,  -6,  22,  6,    51, 37,  -38, 5,   117};
