/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_2_input[60] = {80,  16,   -80,  -96, 96,  -64,  -112, -112, 48,   16,  -80, -80,  80,  64,  -80,
                                       16,  48,   -112, 0,   48,  96,   -80,  -112, -64,  -32, -16, -112, -64, -64, 80,
                                       -96, -112, -16,  -80, -80, -112, -64,  -48,  16,   64,  32,  48,   16,  64,  16,
                                       -48, -64,  -32,  -80, 64,  -48,  -32,  -32,  -112, 32,  32,  -112, -96, -96, 48};
