/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_2_output_ref[60] = {8,   -48, -96, -24, 56,  -21, -59, -37, 5,   11, -43, -48,  -48, 37,   -5,
                                            11,  -37, -48, 0,   -21, 32,  -48, -96, -43, 32, -5,  -101, -64, -69,  -11,
                                            -75, -96, -43, -43, 21,  -59, -43, -16, 0,   0,  -43, -27,  -21, 0,    48,
                                            -21, -16, -16, -43, 37,  -21, -69, -53, -96, 48, -8,  -72,  -64, -104, 40};
