// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define BASIC_OUT_CH 1
#define BASIC_IN_CH 1
#define BASIC_INPUT_W 5
#define BASIC_INPUT_H 8
#define BASIC_DST_SIZE 20
#define BASIC_INPUT_SIZE 40
#define BASIC_OUT_ACTIVATION_MIN -128
#define BASIC_OUT_ACTIVATION_MAX 127
#define BASIC_INPUT_BATCHES 1
#define BASIC_FILTER_X 2
#define BASIC_FILTER_Y 4
#define BASIC_STRIDE_X 1
#define BASIC_STRIDE_Y 1
#define BASIC_PAD_X 0
#define BASIC_PAD_Y 0
#define BASIC_OUTPUT_W 4
#define BASIC_OUTPUT_H 5
#define BASIC_INPUT_OFFSET 128
#define BASIC_OUTPUT_OFFSET 127
#define BASIC_DILATION_X 1
#define BASIC_DILATION_Y 1
