// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t basic_input[40] = {-9,  -38, 76,  -40, 99,  60, 64,  52,  47,  -43, 72, 28,  -82, 61,
                              -63, 48,  -21, -47, 74,  29, -28, 8,   -38, 13,  33, -45, 59,  -25,
                              -8,  -50, 107, 81,  -77, 43, -82, 125, 83,  23,  17, 15};
