// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t basic_output_ref[20] = {127, -128, 63,  -128, -128, 127, 127, 127, -41, 127,
                                   -17, 127,  127, 127,  -128, 127, 127, 127, 127, 127};
