// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define CONV_2_OUT_CH 4
#define CONV_2_IN_CH 2
#define CONV_2_INPUT_W 6
#define CONV_2_INPUT_H 3
#define CONV_2_DST_SIZE 72
#define CONV_2_INPUT_SIZE 36
#define CONV_2_OUT_ACTIVATION_MIN -101
#define CONV_2_OUT_ACTIVATION_MAX 127
#define CONV_2_INPUT_BATCHES 1
#define CONV_2_FILTER_X 3
#define CONV_2_FILTER_Y 3
#define CONV_2_STRIDE_X 1
#define CONV_2_STRIDE_Y 1
#define CONV_2_PAD_X 1
#define CONV_2_PAD_Y 1
#define CONV_2_OUTPUT_W 6
#define CONV_2_OUTPUT_H 3
#define CONV_2_INPUT_OFFSET 128
#define CONV_2_OUTPUT_OFFSET -9
#define CONV_2_DILATION_X 1
#define CONV_2_DILATION_Y 1
