// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2_input[36] = {49, -29, 25, -87, 101, 108, 68, -24, -98, 11,  92,  120, -26, -114, 23, 40, -35, -18,
                               13, -13, 70, 27,  95,  -74, 80, 106, 117, -63, -95, -71, -20, 47,   32, 62, 10,  -96};
