/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#pragma once
// Generated by generate_test_data.py
#include <stdint.h>

const q7_t conv_2_output_ref[72] =
{
  3,
  -1,
  1,
  -1,
  -4,
  -2,
  -1,
  -3,
  -7,
  0,
  -3,
  1,
  -2,
  -2,
  0,
  3,
  0,
  -1,
  -2,
  8,
  8,
  -1,
  -2,
  -3,
  -6,
  -7,
  5,
  2,
  0,
  6,
  14,
  0,
  0,
  -6,
  -3,
  3,
  3,
  6,
  9,
  -2,
  -4,
  -2,
  6,
  -5,
  -6,
  -1,
  -5,
  3,
  -3,
  4,
  4,
  -6,
  -5,
  -2,
  7,
  -6,
  -2,
  0,
  6,
  -6,
  0,
  1,
  0,
  3,
  -1,
  -9,
  7,
  -1,
  -7,
  9,
  7,
  -8
};
