/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2_output_ref[72] = {
    25, -9,  7,   -65, 68, -21, 46,   -56,  46, -15, 32,  -95, 52, 9,  0,   -87, 67, -6, 64,  -57,  87, -24, -11, -83,
    87, -41, -8,  -67, 83, -22, -12,  -100, 37, 52,  -9,  -46, 38, 17, 72,  -91, 68, -3, -8,  -101, 37, 39,  -86, -43,
    70, -46, -33, -54, 43, 22,  -101, -51,  10, 43,  -30, -16, 42, 1,  -34, -37, 43, 15, -55, -18,  25, 37,  -42, -31};
