/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2_output_ref[72] = {23, 22, 32, 30, 38, 39, 49, 43, 43, 45, 60, 50, 48, 47, 63, 56, 47, 42,
                                    55, 48, 29, 27, 34, 26, 35, 41, 53, 45, 61, 61, 76, 61, 69, 77, 92, 78,
                                    69, 76, 92, 81, 66, 69, 89, 69, 42, 42, 49, 38, 27, 37, 40, 32, 41, 50,
                                    59, 45, 47, 62, 67, 56, 50, 62, 68, 55, 46, 59, 67, 51, 27, 33, 38, 29};
