/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2_weights[72] = {-66, -78, 89,   -81,  21,  71,  -14, 65,   -9,  46,   19,   -17, 14,  -38, 119,
                                 127, -71, -42,  56,   96,  -70, 127, -33,  -25, 42,   30,   -62, -38, -46, -13,
                                 79,  -13, -96,  -101, 79,  19,  88,  83,   -24, -104, -114, -30, -13, -12, -106,
                                 126, 109, 47,   89,   -89, 53,  119, 5,    127, -100, 62,   51,  19,  57,  -108,
                                 54,  37,  -127, -25,  77,  -27, 7,   -106, 30,  -114, -65,  -31};
