// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_biases[8] = {3864101, -2174812, -4273364, -1538703, 2379869, 1637715, 842417, 3285024};
