// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_output_mult[8] =
    {1814563076, 1795978464, 1686052907, 1782534381, 1817839397, 1745817143, 1660576855, 1657639441};
