/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#define AVGPOOLING_1_OUT_CH 3
#define AVGPOOLING_1_IN_CH 3
#define AVGPOOLING_1_INPUT_W 9
#define AVGPOOLING_1_INPUT_H 5
#define AVGPOOLING_1_DST_SIZE 3
#define AVGPOOLING_1_INPUT_SIZE 135
#define AVGPOOLING_1_OUT_ACTIVATION_MIN -128
#define AVGPOOLING_1_OUT_ACTIVATION_MAX 127
#define AVGPOOLING_1_INPUT_BATCHES 1
#define AVGPOOLING_1_FILTER_X 9
#define AVGPOOLING_1_FILTER_Y 5
#define AVGPOOLING_1_STRIDE_X 1
#define AVGPOOLING_1_STRIDE_Y 2
#define AVGPOOLING_1_PAD_X 0
#define AVGPOOLING_1_PAD_Y 0
#define AVGPOOLING_1_OUTPUT_W 1
#define AVGPOOLING_1_OUTPUT_H 1
