/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_1_input[135] = {
    -32, 48,  -64, -80, -48,  -32,  -32, 0,    -96,  96,  -48, 80,  -16, -96,  80,  -16, 48,   -112, 96,  -112,
    -96, -64, -16, 96,  0,    -32,  -16, 0,    64,   48,  -64, 0,   0,   -16,  -48, -16, -112, 16,   -80, 64,
    48,  0,   64,  32,  64,   -48,  -64, -32,  -112, 32,  32,  64,  32,  -112, -48, -16, 16,   96,   64,  -16,
    80,  -48, -16, 48,  -32,  -112, -48, -64,  -96,  96,  -16, -16, -32, 48,   16,  -32, -32,  0,    -48, 32,
    48,  0,   -48, 64,  64,   -112, 32,  -112, -16,  80,  -48, 96,  -80, 16,   -80, -32, -64,  -48,  64,  -112,
    16,  -32, -96, 0,   -112, -112, -48, -32,  32,   -64, -32, 32,  96,  48,   96,  48,  96,   -64,  -48, 64,
    96,  64,  -96, -64, 0,    80,   -96, 32,   -16,  0,   96,  -64, -16, 16,   -64};
