// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_1_input_sequence[42] = {-116, 46,  -102, 125, 27,  -49, -64,  72, 13, 117, -119, 79,  -94,  1,
                                        -77,  31,  38,   -15, 9,   65,  -102, 30, 10, -30, 16,   -52, 64,   106,
                                        31,   -59, -78,  -14, -68, 99,  3,    53, 7,  109, -3,   -77, -126, -14};
