// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_1_output_ref[15] = {5, 6, 28, 58, -57, 12, -27, 8, -52, 63, -14, 18, -35, 37, -50};
