// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_1_weights_feature[35] = {83, 21,  61, 103, 52,   2,   -28, 6,   38,   -10,  25,  -83,
                                         92, -64, 48, 66,  -4,   57,  40,  108, 39,   -109, -56, -91,
                                         63, 118, 76, -21, -126, 104, -94, -70, -116, 60,   -82};
