// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_out_activation_input[10] = {-11, 119, -74, 109, -34, 59, 96, 2, -115, 55};
