// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_out_activation_weights[40] = {
    -96, -9,  -64, -4, -105, -92, 77, 90, 15,  109, -121, 84, 78,   107, 48, -55, 10, 29,   47,   -120,
    -1,  -55, 14,  98, 36,   51,  0,  43, -29, 7,   87,   98, -106, 109, 40, -66, 30, -127, -125, -124};
