/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_out_activation_weights[40] = {3,  11,  1,   -6, 8,   11, -14, -6, 10,  3,  1,  9, -6, 8,
                                                         12, -13, -10, 11, -14, 0,  7,   9,  -15, 14, 13, 5, 7,  -2,
                                                         4,  -4,  -7,  -6, -13, -7, -15, -2, -3,  11, 14, -1};
