// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#define CONV_1_X_N_2_OUT_CH 5
#define CONV_1_X_N_2_IN_CH 4
#define CONV_1_X_N_2_INPUT_W 8
#define CONV_1_X_N_2_INPUT_H 1
#define CONV_1_X_N_2_DST_SIZE 20
#define CONV_1_X_N_2_INPUT_SIZE 32
#define CONV_1_X_N_2_OUT_ACTIVATION_MIN -111
#define CONV_1_X_N_2_OUT_ACTIVATION_MAX 127
#define CONV_1_X_N_2_INPUT_BATCHES 1
#define CONV_1_X_N_2_FILTER_X 4
#define CONV_1_X_N_2_FILTER_Y 1
#define CONV_1_X_N_2_STRIDE_X 2
#define CONV_1_X_N_2_STRIDE_Y 1
#define CONV_1_X_N_2_PAD_X 1
#define CONV_1_X_N_2_PAD_Y 0
#define CONV_1_X_N_2_OUTPUT_W 4
#define CONV_1_X_N_2_OUTPUT_H 1
#define CONV_1_X_N_2_INPUT_OFFSET 128
#define CONV_1_X_N_2_OUTPUT_OFFSET 96
#define CONV_1_X_N_2_DILATION_X 1
#define CONV_1_X_N_2_DILATION_Y 1
