/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#define CONV_1_X_N_2_OUT_CH 1
#define CONV_1_X_N_2_IN_CH 3
#define CONV_1_X_N_2_INPUT_W 11
#define CONV_1_X_N_2_INPUT_H 11
#define CONV_1_X_N_2_DST_SIZE 121
#define CONV_1_X_N_2_INPUT_SIZE 363
#define CONV_1_X_N_2_OUT_ACTIVATION_MIN -128
#define CONV_1_X_N_2_OUT_ACTIVATION_MAX 127
#define CONV_1_X_N_2_INPUT_BATCHES 1
#define CONV_1_X_N_2_INPUT_OFFSET 0
#define CONV_1_X_N_2_OUTPUT_OFFSET 0
#define CONV_1_X_N_2_FILTER_X 11
#define CONV_1_X_N_2_FILTER_Y 1
#define CONV_1_X_N_2_STRIDE_X 1
#define CONV_1_X_N_2_STRIDE_Y 1
#define CONV_1_X_N_2_PAD_X 5
#define CONV_1_X_N_2_PAD_Y 0
#define CONV_1_X_N_2_OUTPUT_W 11
#define CONV_1_X_N_2_OUTPUT_H 11
