// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_2_input[32] = {103, -12, 82, -63, -29, -125, 117, 126, -40, -58, -34, 61, -37, -97, -21, 63,
                                     -44, 44,  49, 30,  -1,  62,   2,   125, 38,  118, 81,  85, -90, -23, -22, -33};
