// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_2_output_ref[20] = {125, 71,  123, 31, -60, 67, 127, 109, 55, -1,
                                          76,  122, 113, 66, -39, 34, 63,  111, 68, 31};
