/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_2_output_ref[121] = {
    9,  5,  21, 17, 6,  8,  19, 14, 18, 15, -2, 4,  7,  5,  15, 2,  0,  17, 8, 23, 10, 10, 0,  5,  4,
    15, 3,  23, 5,  18, 6,  15, 10, 14, 5,  -2, 16, 15, 11, 23, 11, 7,  9,  5, 0,  8,  3,  -1, 16, 11,
    14, 19, 7,  10, 10, 3,  1,  2,  -2, 2,  -1, 20, 4,  12, 9,  7,  6,  -3, 0, -2, 8,  2,  14, 6,  2,
    7,  7,  -1, 4,  -3, 12, 10, 15, 11, 10, 7,  3,  16, 1,  -6, 7,  -4, 7,  3, 15, 13, 1,  17, -8, 8,
    11, 6,  2,  2,  18, 1,  17, 8,  -1, 7,  -3, 5,  3,  2,  -3, 10, 4,  23, 7, 12, 14};
