// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const int32_t conv_1_x_n_2_output_mult[5] = {1309548775, 1226402783, 1299155536, 1309548775, 1278369058};
