// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_2_weights[33] = {-61, 123, -127, -46, 36,  -99, -58, -22, 91,  19, 88,
                                       23,  26,  -61,  98,  -99, 1,   97,  21,  -47, 20, 48,
                                       -54, 78,  -125, -52, -23, -64, -54, -79, -6,  84, 120};
