// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_2_weights[16] = {59, 28, -23, -8, 53, 25, -18, -98, -108, -9, -127, 125, -84, -12, 11, -77};
