// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2x2_dilation_5x5_input_input[50] = {
    -102, -14, 21,   -74,  -119, 89,  39,   55,  -84,  -51,  -44, -33, -92, 2,   85,  -8,  -11,
    56,   -58, -122, 68,   91,   -65, -77,  -79, 52,   124,  82,  19,  22,  -58, -54, -96, 87,
    49,   -84, -99,  -108, 15,   25,  -103, 36,  -119, -128, 107, -69, -72, -52, 55,  -120};
