// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2x2_dilation_5x5_input_output_ref[50] = {
    60, 1,  82, 33, 89,  28,  99, -2,  55, 59, 101, 40, 94, 23, 87, 19,  88, 72, 87, 43, 107, 4,  89, 31, 62,
    24, 91, -2, 91, -16, 106, 21, 107, 21, 69, 41,  53, 69, 74, 39, 107, 30, 87, 42, 69, -41, 82, 68, 79, 63};
