// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2x2_dilation_5x5_input_weights[36] = {
    -125, -31, -51, 26,  -25,  41,  14, -127, 58,   100,  56,  -62, 103,  -49, -62, -6,   7,  -74,
    -94,  -92, 120, -99, -105, -34, 76, 41,   -110, -104, -77, -2,  -127, 103, -99, -109, 92, -99};
