// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int64_t fc_int16_slow_biases[11] =
    {4154170, 4149344, 4152773, 4159504, 4155440, 4152646, 4148963, 4160139, 4149090, 4149979, 4156837};
