// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t fc_int16_slow_output_ref[33] = {32762, 32762, 32762, 32762, 32762, 32762, 32762, 32762, 32762,
                                            32762, 32762, 32764, 32763, 32763, 32764, 32764, 32763, 32763,
                                            32764, 32763, 32763, 32764, 32763, 32763, 32763, 32763, 32763,
                                            32763, 32763, 32763, 32763, 32763, 32763};
