// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_3_output_ref[10] = {-38, 110, -85, -30, -103, 124, -118, 6, 42, 101};
