/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_mult_batches_input[90] = {
    68, -38, -62,  92,  27,  -50,  0,    123,  88,   -39, 7,   -105, -91, 84,  -31,  -46, -37, -32,
    94, 118, 64,   113, 1,   -30,  -31,  -107, -53,  -15, 42,  -14,  75,  -86, 18,   -43, 64,  -22,
    66, -76, 45,   70,  -84, 32,   -73,  99,   3,    -73, 113, 7,    -13, 51,  -119, -21, 51,  -92,
    -1, 52,  -127, 86,  -85, -104, -18,  -39,  64,   -91, -59, 80,   9,   -53, -118, 9,   81,  -10,
    31, 85,  72,   35,  38,  87,   -112, -91,  -103, 49,  56,  51,   7,   54,  74,   81,  35,  54};
