// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_mult_batches_output_mult[3] = {1541073024, 1440840587, 1503485896};
