// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_mult_batches_output_ref[36] = {6,   21,  57,  -6,  16,  61, 5,   -29, 98, -5,  0,  42,
                                                    -97, -31, 21,  -8,  -26, 26, 44,  25,  56, 2,   7,  54,
                                                    5,   -7,  127, -10, -11, 35, -79, -56, 15, -32, -1, 38};
