// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_mult_batches_weights[24] = {-21, -127, -59, -127, -113, 74,  -121, 12,  88, -101, -4, -111,
                                                 59,  85,   81,  97,   49,   127, 38,   -31, 61, 126,  -4, 49};
