// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t requantize_s64_input[12] = {82, 66, -30, -105, 95, 74, 124, 93, -25, 93, 57, -32};
