// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t requantize_s64_weights[16] = {-23, 101, 3, -55, -120, 127, -120, 6, 103, 103, -95, 60, 102, 9, -60, -90};
