// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_multiple_batches_uneven_buffers_null_bias_output_mult[8] =
    {1321976810, 1963386025, 1097671686, 1316291179, 1344377358, 1921833836, 1832060491, 1383450161};
