// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_multiple_batches_uneven_buffers_null_bias_output_shift[8] =
    {-7, -9, -7, -7, -7, -8, -8, -7};
