/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_out_activation_weights[36] = {-4,  -65, -85, -9, -108, -106, -17,  17,  93,  -97, -127, 23,
                                              -81, 42,  -12, 0,  29,   40,   -90,  -74, -10, -42, 74,   -104,
                                              -58, 74,  17,  5,  -58,  123,  -127, 59,  -90, -5,  16,   -104};
