// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_out_activation_weights[36] = {-4,  -65, -85, -9, -108, -106, -17,  17,  93,  -97, -127, 23,
                                              -81, 42,  -12, 0,  29,   40,   -90,  -74, -10, -42, 74,   -104,
                                              -58, 74,  17,  5,  -58,  123,  -127, 59,  -90, -5,  16,   -104};
