// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_fast_test_bias_biases[8] =
    {-795878, -5334291, 1236759, -5395949, 1406307, -3500813, 1515920, -1889120};
