// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const q7_t dw_int16xint8_fast_test_bias_weights[32] = {7,   -117, -110, -16, -102, -127, -3,   -19,  107, -1, -95,
                                                       127, 68,   -24,  122, -18,  -127, -127, -127, 12,  -3, -49,
                                                       -22, -127, 1,    15,  -90,  -97,  -127, 84,   127, -38};
