// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t int16xint8_dilation_2_output_mult[4] = {1566522842, 1222196941, 1511961819, 1495244605};
