// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_dilation_biases[9] = {12495, 6149, 15927, -28852, 11638, 36212, -25966, -518, -39439};
