// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_dilation_output_mult[9] =
    {1253719158, 1559745097, 1204360159, 1085898488, 1263590957, 1085898488, 1095770288, 1233975558, 1994104433};
