// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_fast_stride_biases[8] =
    {3857514, 5638784, 8961266, -2293409, 4619095, 103948, -4048063, -6682};
