// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_stride_output_mult[8] =
    {1784496138, 1642220715, 2046506384, 1301716135, 1299541769, 1130159169, 2094197358, 1150996765};
