// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_stride_output_shift[8] = {-8, -8, -9, -8, -8, -7, -8, -7};
