// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_spill_output_mult[5] = {1553785464, 1553640309, 1455315992, 1553688694, 1507139513};
