// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t dw_int16xint8_fast_spill_weights[45] = {-53,  57,  127,  39,   -127, 127,  31,   -54, -79, -23,  93,   -23,
                                                   -51,  23,  -121, -118, 59,   -27,  120,  109, -1,  -29,  -105, -90,
                                                   114,  -94, -41,  -8,   45,   -70,  -107, 93,  66,  -127, 120,  5,
                                                   -101, 73,  13,   -9,   -96,  -127, -69,  -96, -64};
