// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_output_mult[8] =
    {1361622559, 2061085920, 1439025284, 2049907986, 1166718462, 1358561950, 1389523040, 1162859479};
