// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int16_t avgpooling_int16_1_input[18] = {23269,
                                              -14726,
                                              15968,
                                              -32485,
                                              14383,
                                              26655,
                                              -5510,
                                              9514,
                                              15927,
                                              9348,
                                              9806,
                                              -11972,
                                              4272,
                                              -17618,
                                              21518,
                                              -1399,
                                              -5680,
                                              -16677};
