// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int16_t avgpooling_int16_1_output_ref[10] =
    {23269, -14726, 14383, 26655, 15927, 9348, 4272, -17618, -5680, -16677};
