// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t fully_connected_mve_0_biases[9] = {22875, 25959, 12080, -28787, -23646, 5655, 2056, -18506, 15421};
