// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_mve_0_output_ref[9] = {63, -6, -95, -5, -84, -128, -61, 17, 19};
