// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_biases[17] = {63742,
                                      -25567,
                                      15168,
                                      -36287,
                                      7303,
                                      46323,
                                      5280,
                                      25782,
                                      16909,
                                      -6375,
                                      -14790,
                                      10560,
                                      -16751,
                                      23793,
                                      -263,
                                      -8016,
                                      -19538};
