// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_biases[9] = {29485, -24136, 15133, -33237, 16751, 9118, -8233, -14644, 18913};
