
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
// Generated by generate_test_data.py
#include <stdint.h>

const q7_t kernel1x1_output_ref[64] =
{
  -24,
  43,
  19,
  42,
  13,
  36,
  41,
  -19,
  -20,
  -17,
  16,
  -21,
  48,
  22,
  -41,
  -31,
  -29,
  17,
  -53,
  22,
  -19,
  -12,
  -29,
  -37,
  50,
  4,
  36,
  13,
  42,
  18,
  -1,
  11,
  23,
  42,
  -28,
  32,
  -15,
  12,
  24,
  -9,
  11,
  -32,
  -13,
  15,
  32,
  -17,
  4,
  42,
  37,
  -54,
  -9,
  -4,
  33,
  7,
  29,
  32,
  -19,
  27,
  38,
  28,
  30,
  -13,
  5,
  -3
};
