// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_output_mult[9] =
    {2021105711, 1598785192, 1613868063, 1719448165, 1749613908, 1553536463, 1779779651, 1734531036, 1885359867};
