// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_output_mult[17] = {1874319815,
                                           1413177635,
                                           1175168771,
                                           1234670959,
                                           1517306464,
                                           1175168771,
                                           1368550994,
                                           1532182011,
                                           1680937593,
                                           1889195362,
                                           1889195362,
                                           1368550994,
                                           1725564233,
                                           1457804276,
                                           1829693175,
                                           1502430917,
                                           1799942081};
