// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t kernel1x1_weights[45] = {-119, 118,  -85, 127, 17,  23,  -47, 127, 65,   102, 23, 106, 127, 6,    -9,
                                    17,   -2,   71,  -98, 127, 74,  10,  78,  -127, 102, 97, 84,  127, -89,  -30,
                                    13,   -126, 89,  127, 0,   -94, 123, 83,  127,  -92, 76, 19,  -26, -127, -42};
