/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t kernel1x1_weights[68] = {127,  81,   89,   36,   -104, 15,   -29,  -127, 127, -124, 127,  -39,  127,  -90,
                                    -50,  -54,  0,    106,  -111, -127, -127, -79,  34,  11,   -127, 69,   -32,  94,
                                    -127, -115, 92,   -76,  127,  -35,  -120, 83,   -1,  92,   34,   -127, -127, 3,
                                    -124, 13,   -127, 35,   50,   -91,  -21,  11,   127, 124,  -60,  127,  0,    61,
                                    -98,  74,   21,   -127, -127, 26,   -72,  20,   -87, 127,  97,   -8};
