// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2x2_dilation_weights[36] = {123,  -12, -70, -76, -55, -124, 3,   96,  -70,  97,  90,  -124,
                                            -127, -1,  -93, 56,  24,  -103, 2,   87,  -32,  -81, -51, -41,
                                            -89,  -45, -20, 74,  101, 68,   -17, 111, -127, -61, 115, 5};
