dct:
  config1_f32: 
    melFilters: 20 
    dctOutputs: 13
    type: "f32"

melfilter:
  config1_f32 : 
    fftlength: 256 
    fmin: 64 
    fmax: 8000 
    samplingRate : 16000 
    melFilters: 20 
    type: "f32"  

window:
  config1_f32:
    fftlength: 256 
    type: "f32"  
    win: "hamming"
