/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#define INT16XINT8_OUT_CH 4
#define INT16XINT8_IN_CH 3
#define INT16XINT8_INPUT_W 7
#define INT16XINT8_INPUT_H 8
#define INT16XINT8_DST_SIZE 48
#define INT16XINT8_INPUT_SIZE 168
#define INT16XINT8_OUT_ACTIVATION_MIN -32768
#define INT16XINT8_OUT_ACTIVATION_MAX 32767
#define INT16XINT8_INPUT_BATCHES 1
#define INT16XINT8_INPUT_OFFSET 0
#define INT16XINT8_OUTPUT_OFFSET 0
#define INT16XINT8_FILTER_X 2
#define INT16XINT8_FILTER_Y 4
#define INT16XINT8_STRIDE_X 2
#define INT16XINT8_STRIDE_Y 3
#define INT16XINT8_PAD_X 0
#define INT16XINT8_PAD_Y 1
#define INT16XINT8_OUTPUT_W 4
#define INT16XINT8_OUTPUT_H 3
