// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t int16xint8_output_mult[4] = {1388772064, 1391969415, 1360038279, 1365367254};
