/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t int16xint8_output_ref[48] = {
    -6939, -7913, -10478, 2083,  4909,   -7615, -12139, 56,   -2031,  -239,  -1461, 12852, -5087, -4686, -6984,  4797,
    -7156, -9860, 2349,   4743,  -10003, -1689, -4330,  159,  14093,  -5456, -8866, -1445, 2552,  3120,  -13335, -10211,
    -4546, -7367, 95,     -1593, -9522,  6399,  -8913,  3013, -10355, 13874, 8880,  8500,  -4208, 703,   -7717,  2509};
