/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t int16xint8_weights[96] = {
    -113, 41,  -99,  -23, -59,  -65, -88,  -123, 83,   127, -121, 97,  -96, -94,  52,  -8,   6,    -6,  90,   15,
    87,   111, -56,  -42, 80,   115, -1,   72,   116,  107, 67,   124, -50, -30,  -6,  23,   -127, 102, 58,   64,
    34,   52,  111,  19,  -104, -2,  -95,  -125, 77,   -16, -5,   20,  -21, -3,   91,  -124, -47,  -83, -67,  -3,
    124,  111, 101,  -21, 79,   127, -124, 69,   -15,  -82, 11,   113, 46,  -102, 95,  32,   -32,  -7,  -114, -102,
    32,   62,  -127, 87,  83,   -3,  -67,  97,   -100, -7,  34,   -73, 99,  -61,  -15, -104};
