/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t int16xint8_weights[96] = {
    32,   -127, 64,   -95, 0,    0,    95,   -64, -127, 0,   -64, -64,  -127, 32,  32,   -32, -95, -95, 64,  64,
    0,    0,    -127, 0,   -95,  -95,  -127, -32, 0,    0,   -95, 0,    -64,  95,  -127, -32, 32,  0,   -64, -95,
    -127, -64,  64,   -32, -127, -64,  -64,  0,   -32,  -95, 0,   -127, 64,   32,  64,   64,  -95, 32,  -64, -64,
    32,   -64,  0,    95,  -127, -127, -95,  95,  -64,  -64, -64, -127, -64,  95,  32,   95,  95,  95,  0,   64,
    -64,  -32,  -127, 64,  -127, 32,   64,   95,  -127, 64,  64,  -95,  95,   -64, -95,  95};
