/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#define MAXPOOLING_4_OUT_CH 2
#define MAXPOOLING_4_IN_CH 2
#define MAXPOOLING_4_INPUT_W 1
#define MAXPOOLING_4_INPUT_H 20
#define MAXPOOLING_4_DST_SIZE 14
#define MAXPOOLING_4_INPUT_SIZE 40
#define MAXPOOLING_4_OUT_ACTIVATION_MIN -128
#define MAXPOOLING_4_OUT_ACTIVATION_MAX 127
#define MAXPOOLING_4_INPUT_BATCHES 1
#define MAXPOOLING_4_FILTER_X 1
#define MAXPOOLING_4_FILTER_Y 3
#define MAXPOOLING_4_STRIDE_X 1
#define MAXPOOLING_4_STRIDE_Y 3
#define MAXPOOLING_4_PAD_X 0
#define MAXPOOLING_4_PAD_Y 0
#define MAXPOOLING_4_OUTPUT_W 1
#define MAXPOOLING_4_OUTPUT_H 7
