// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_4_input[40] = {-117, -127, -44, 5,   13,  5,   26,   -115, -33,  -102, 91,   45, 68,  52,
                                       60,   93,   96,  -73, -29, -46, -128, 62,   -108, 20,   67,   84, 109, -67,
                                       -70,  -99,  -10, -60, -55, -9,  56,   -60,  -74,  -52,  -126, 14};
