// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_4_output_ref[14] = {13, 5, 91, 45, 96, 93, -29, 62, 109, 84, 56, -9, -74, 14};
