
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
// Generated by generate_test_data.py
#define STRIDE2PAD1_OUT_CH 1
#define STRIDE2PAD1_IN_CH 1
#define STRIDE2PAD1_CONV_W 7
#define STRIDE2PAD1_CONV_H 7
#define STRIDE2PAD1_FILTER_X 3
#define STRIDE2PAD1_FILTER_Y 3
#define STRIDE2PAD1_STRIDE_X 2
#define STRIDE2PAD1_STRIDE_Y 2
#define STRIDE2PAD1_PAD_X 1
#define STRIDE2PAD1_PAD_Y 1
#define STRIDE2PAD1_OUT_CONV_W 4
#define STRIDE2PAD1_OUT_CONV_H 4
#define STRIDE2PAD1_DST_SIZE 16
#define STRIDE2PAD1_INPUT_SIZE 49
#define STRIDE2PAD1_INPUT_OFFSET 0
#define STRIDE2PAD1_OUTPUT_OFFSET 0
#define STRIDE2PAD1_OUT_ACTIVATION_MIN -128
#define STRIDE2PAD1_OUT_ACTIVATION_MAX 127
#define STRIDE2PAD1_INPUT_BATCHES 1
