// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t stride2pad1_input[49] = {27,   70,  -117, 45,   99,   100,  107, -24, 5,   75,  106,  -19, -70,
                                    -123, 30,  55,   24,   -49,  71,   36,  -35, -46, -96, -102, -15, -127,
                                    121,  37,  -37,  -10,  -115, 82,   53,  -60, -74, 38,  -109, 4,   53,
                                    -95,  120, 5,    -122, -71,  -117, 6,   39,  61,  88};
