/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t stride2pad1_input[49] = {27,   70,  -117, 45,   99,   100,  107, -24, 5,   75,  106,  -19, -70,
                                    -123, 30,  55,   24,   -49,  71,   36,  -35, -46, -96, -102, -15, -127,
                                    121,  37,  -37,  -10,  -115, 82,   53,  -60, -74, 38,  -109, 4,   53,
                                    -95,  120, 5,    -122, -71,  -117, 6,   39,  61,  88};
