/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_3_output_ref[250] = {
    21, 41, -26, 3,  22, 21, 17, 14, 20, 13, 6,   31, 28, 18, 27, -1, 22, 41, 29,  5,  27, 36, 25, 23, 13,  32, 38, 16,
    -3, 23, 48,  48, 34, 30, 25, 53, -1, 10, 16,  13, 43, 9,  32, 22, 24, 40, 25,  37, 26, 22, 32, 29, 41,  10, 32, 35,
    37, 10, 23,  32, 50, 31, 23, 18, 34, 30, 24,  38, 29, 12, 8,  28, 43, 19, 5,   20, 15, 21, 22, 15, 24,  23, 29, 52,
    40, 38, 19,  34, 27, 23, 8,  7,  14, 29, 45,  33, 20, 28, 25, 2,  3,  27, 30,  10, -8, 53, 23, 27, 28,  4,  27, 8,
    -4, 20, 25,  39, 16, 43, 0,  1,  29, 46, 32,  -7, -5, 4,  58, 46, 18, 12, 17,  33, 27, 33, 42, 16, 11,  30, 31, 17,
    41, 53, 37,  9,  13, 4,  51, 33, 24, 10, 1,   29, 43, 21, 47, 23, 33, 39, 21,  17, 19, 12, 4,  27, 16,  27, 48, 46,
    40, 11, -1,  18, 26, 54, 45, 53, 8,  38, 24,  30, 28, 19, 43, 38, 26, 27, 39,  20, -5, 14, -5, 4,  14,  9,  10, 30,
    14, 9,  34,  6,  14, 19, 19, 23, -2, 16, -12, 33, 22, 11, 31, 8,  9,  22, 18,  13, -3, 47, -3, 26, -13, 39, 24, 23,
    5,  18, 25,  7,  13, 23, 21, 23, 24, 16, 15,  14, 6,  29, 6,  8,  17, -1, -11, 2,  17, 4,  13, -2, -2,  12};
