/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_input[60] = {-48, -54, -49, -49, -51, -47, -49, -49, -52, -54, -48, -48, -54, -53, -53,
                                        -53, -53, -49, -52, -52, -54, -53, -50, -52, -51, -52, -51, -50, -53, -53,
                                        -47, -48, -52, -52, -48, -53, -54, -54, -49, -50, -53, -47, -48, -51, -51,
                                        -47, -53, -53, -51, -51, -47, -54, -50, -50, -49, -47, -48, -50, -50, -51};
