/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_output_ref[72] = {
    -29, 10,  -42, 9,   -32, -10, -2,  2,   -10, -28, -20, 3,   6,  10,  -27, -17, 14,  4, -2,  -42, -21, -4,  0,   -22,
    -12, -20, -16, 12,  10,  -14, 3,   -28, -15, -16, -3,  -21, -4, -9,  -30, -10, -13, 6, -15, 3,   -4,  -18, -12, -15,
    -21, -25, -11, -13, 10,  -7,  -14, -10, -15, 20,  -8,  11,  3,  -34, -19, -20, -14, 2, -9,  -31, -26, 17,  3,   4};
