/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#define MAXPOOLING_6_OUT_CH 17
#define MAXPOOLING_6_IN_CH 17
#define MAXPOOLING_6_INPUT_W 1
#define MAXPOOLING_6_INPUT_H 5
#define MAXPOOLING_6_DST_SIZE 34
#define MAXPOOLING_6_INPUT_SIZE 85
#define MAXPOOLING_6_OUT_ACTIVATION_MIN -128
#define MAXPOOLING_6_OUT_ACTIVATION_MAX 127
#define MAXPOOLING_6_INPUT_BATCHES 1
#define MAXPOOLING_6_FILTER_X 3
#define MAXPOOLING_6_FILTER_Y 4
#define MAXPOOLING_6_STRIDE_X 1
#define MAXPOOLING_6_STRIDE_Y 3
#define MAXPOOLING_6_PAD_X 1
#define MAXPOOLING_6_PAD_Y 1
#define MAXPOOLING_6_OUTPUT_W 1
#define MAXPOOLING_6_OUTPUT_H 2
