// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_6_output_ref[34] = {72, 103, 85, -15, 91, 96, -41, 85, 80, 111, 46, 80, 115, -52, 117, -14, 60,
                                            75, -41, 65, 23,  41, 94, 76,  85, 80, 111, 36, 43, 115, 123, 125, 118, 29};
