// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define CONV_1_X_N_1_OUT_CH 3
#define CONV_1_X_N_1_IN_CH 3
#define CONV_1_X_N_1_INPUT_W 5
#define CONV_1_X_N_1_INPUT_H 5
#define CONV_1_X_N_1_DST_SIZE 60
#define CONV_1_X_N_1_INPUT_SIZE 75
#define CONV_1_X_N_1_OUT_ACTIVATION_MIN -127
#define CONV_1_X_N_1_OUT_ACTIVATION_MAX 127
#define CONV_1_X_N_1_INPUT_BATCHES 2
#define CONV_1_X_N_1_FILTER_X 2
#define CONV_1_X_N_1_FILTER_Y 1
#define CONV_1_X_N_1_STRIDE_X 2
#define CONV_1_X_N_1_STRIDE_Y 1
#define CONV_1_X_N_1_PAD_X 0
#define CONV_1_X_N_1_PAD_Y 0
#define CONV_1_X_N_1_OUTPUT_W 2
#define CONV_1_X_N_1_OUTPUT_H 5
#define CONV_1_X_N_1_INPUT_OFFSET 128
#define CONV_1_X_N_1_OUTPUT_OFFSET -128
#define CONV_1_X_N_1_DILATION_X 1
#define CONV_1_X_N_1_DILATION_Y 1
