// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_1_weights[18] = {-22, 44, -127, 81, -8, 38, 73, -127, 70, -86, 88, 35, -3, 26, 101, -65, 127, 88};
