/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_2_input[90] = {-7,  -17, 104, 119,  94,  50,   -104, -48,  4,    123, 73,   -123, -103, -72,  -120,
                                    0,   -23, 11,  95,   -20, -33,  123,  -108, 51,   94,  90,   67,   -48,  25,   28,
                                    -76, -34, 6,   -91,  -88, -110, 87,   -82,  10,   -39, -104, -55,  82,   15,   68,
                                    40,  112, 75,  61,   89,  10,   -41,  72,   63,   44,  -122, 32,   93,   -8,   -37,
                                    3,   28,  -17, 21,   -2,  36,   -120, 15,   -99,  45,  53,   45,   -18,  -103, -64,
                                    -64, -68, 114, -118, 94,  29,   -37,  -67,  -123, -24, -86,  99,   -72,  102,  -63};
