// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_2_output_mult[9] =
    {1133287388, 1161155097, 1123998152, 1151865861, 1096130373, 1133287388, 1179733569, 1189022806, 1114708915};
