// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_dilation_output_mult[8] =
    {1549993836, 1706358422, 1667941929, 1727736113, 1677837094, 1633388220, 1653496022, 1592431848};
