// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#define CONV_1_X_N_3_OUT_CH 3
#define CONV_1_X_N_3_IN_CH 1
#define CONV_1_X_N_3_INPUT_W 12
#define CONV_1_X_N_3_INPUT_H 2
#define CONV_1_X_N_3_DST_SIZE 36
#define CONV_1_X_N_3_INPUT_SIZE 24
#define CONV_1_X_N_3_OUT_ACTIVATION_MIN -88
#define CONV_1_X_N_3_OUT_ACTIVATION_MAX 127
#define CONV_1_X_N_3_INPUT_BATCHES 1
#define CONV_1_X_N_3_FILTER_X 1
#define CONV_1_X_N_3_FILTER_Y 11
#define CONV_1_X_N_3_STRIDE_X 1
#define CONV_1_X_N_3_STRIDE_Y 2
#define CONV_1_X_N_3_PAD_X 0
#define CONV_1_X_N_3_PAD_Y 4
#define CONV_1_X_N_3_OUTPUT_W 12
#define CONV_1_X_N_3_OUTPUT_H 1
#define CONV_1_X_N_3_INPUT_OFFSET 128
#define CONV_1_X_N_3_OUTPUT_OFFSET -29
#define CONV_1_X_N_3_DILATION_X 1
#define CONV_1_X_N_3_DILATION_Y 1
