// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define CONV_1_X_N_3_OUT_CH 3
#define CONV_1_X_N_3_IN_CH 1
#define CONV_1_X_N_3_INPUT_W 11
#define CONV_1_X_N_3_INPUT_H 11
#define CONV_1_X_N_3_DST_SIZE 363
#define CONV_1_X_N_3_INPUT_SIZE 121
#define CONV_1_X_N_3_OUT_ACTIVATION_MIN -88
#define CONV_1_X_N_3_OUT_ACTIVATION_MAX 127
#define CONV_1_X_N_3_INPUT_BATCHES 1
#define CONV_1_X_N_3_FILTER_X 1
#define CONV_1_X_N_3_FILTER_Y 11
#define CONV_1_X_N_3_STRIDE_X 1
#define CONV_1_X_N_3_STRIDE_Y 1
#define CONV_1_X_N_3_PAD_X 0
#define CONV_1_X_N_3_PAD_Y 5
#define CONV_1_X_N_3_OUTPUT_W 11
#define CONV_1_X_N_3_OUTPUT_H 11
#define CONV_1_X_N_3_INPUT_OFFSET 128
#define CONV_1_X_N_3_OUTPUT_OFFSET 38
#define CONV_1_X_N_3_DILATION_X 1
#define CONV_1_X_N_3_DILATION_Y 1
