// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_3_input[24] = {48, -99, 102, -110, -50, 84,  15,   31, 97,   114, -21, -114,
                                     59, -45, -64, -119, 90,  -34, -112, -9, -108, 105, -22, -52};
