// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_3_output_ref[36] = {87,  -76, -75, 25,  19,  -78, 11,  -88, -88, -20, 28,  -88,
                                          107, -15, -1,  29,  -88, -88, -18, -51, -88, 45,  -64, -88,
                                          -16, -88, -88, 114, -88, -74, 38,  -30, -88, 21,  29,  -76};
