/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_3_output_ref[363] = {
    3,  2,  -1, 6,  0,  -1, 6,  4,   -4, 8,  -1, 2,  6,  3,  -6, 2,  0,  4,  -3, -3, 0,  7,  0,  2,  3,  0,  3,  4,
    -4, 6,  2,  -8, 1,  0,  -1, -4,  11, 1,  7,  5,  2,  -2, 10, 0,  5,  -2, -3, -5, 6,  1,  -5, -3, -2, 2,  10, 3,
    -1, 7,  0,  -1, 12, 1,  7,  4,   -5, 10, -1, -4, -2, 9,  -2, -5, 5,  -1, -4, 7,  -4, -1, -5, -8, 1,  7,  1,  1,
    -3, -2, -2, 9,  -1, 1,  5,  -1,  -1, 17, 3,  -1, 12, 0,  5,  -3, -5, 3,  3,  -3, 5,  1,  -2, 1,  9,  2,  5,  -4,
    -7, 3,  3,  -5, 0,  1,  2,  0,   6,  -1, -1, 3,  -4, 3,  17, 6,  3,  14, 6,  2,  -1, -7, -1, 6,  -1, 9,  -2, -8,
    3,  12, 7,  9,  0,  -8, 3,  3,   -4, -2, 4,  4,  -1, 3,  0,  7,  6,  0,  1,  14, 6,  4,  9,  5,  5,  3,  2,  2,
    15, 1,  1,  4,  -8, 2,  12, 0,   -3, 6,  -1, 0,  3,  3,  11, 6,  4,  -7, 2,  -4, 4,  11, 5,  6,  14, 2,  3,  10,
    3,  0,  7,  2,  5,  8,  4,  3,   7,  -1, 6,  4,  -3, 3,  9,  6,  4,  11, -5, 1,  0,  1,  0,  6,  -6, 2,  11, -1,
    0,  10, -5, 7,  6,  6,  4,  6,   1,  -7, 8,  -4, 1,  9,  3,  -1, 4,  -4, 4,  6,  8,  -1, 8,  -1, -3, -1, -9, -2,
    4,  2,  2,  8,  -5, -2, 11, -11, 0,  4,  -2, -1, 1,  4,  5,  5,  1,  3,  7,  5,  6,  6,  3,  0,  4,  4,  3,  4,
    3,  8,  -1, -6, -1, 6,  5,  0,   3,  1,  7,  9,  -2, 6,  2,  -8, -3, 1,  -2, 3,  5,  7,  3,  6,  3,  3,  4,  4,
    5,  1,  -3, 2,  7,  1,  1,  1,   -4, 7,  2,  6,  2,  8,  0,  5,  11, 3,  9,  -1, -3, 0,  4,  -3, -6, 5,  -1, 4,
    6,  3,  -1, 5,  -5, -2, 2,  -5,  -7, 6,  4,  2,  6,  -5, -2, 2,  1,  -2, 8,  0,  2,  14, 4,  4,  1,  2,  1};
