// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_3_weights[33] = {85,  -76,  -73, -105, -2,  100, -127, 122, -94, 18,  -84,
                                       -38, -103, -66, -127, -99, -4,  30,   -45, 57,  -58, 29,
                                       113, -117, 18,  115,  -86, 127, 71,   71,  2,   -88, -118};
