// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_3_weights[33] = {-66,  58,  -36, 110,  11,  -55, 127, 16,  23,  -85, -52,
                                       -127, 38,  -66, -9,   109, 9,   -87, 103, 20,  97,  -104,
                                       -54,  -91, 84,  -127, -46, -82, 42,  -90, -63, -69, -111};
