// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_fast_multiple_batches_uneven_buffers_biases[8] =
    {-2863147, 3727567, 647963, 1377393, -795891, 3272794, 2461992, 3993595};
