// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const q7_t dw_int16xint8_fast_multiple_batches_uneven_buffers_weights[72] = {
    -127, 36,  -22,  -31,  -45,  -71, 127, 29,   -91, -95, 127,  -79,  32,   3,    -33,  66,  88,   112,
    -107, 46,  -21,  48,   -115, -70, -58, 1,    61,  -43, -3,   -127, -60,  -77,  -91,  6,   -81,  127,
    -18,  -33, -2,   -122, 6,    -39, -3,  -107, -3,  -36, -113, -120, -121, -116, -118, -18, -107, -75,
    49,   45,  -119, -84,  28,   76,  -72, 26,   63,  127, -107, -127, -126, -43,  127,  -14, 74,   57};
