// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int64_t fully_connected_int16_big_biases[11] =
    {-3933832, 2210749, -2763436, -3803788, -3901321, -3251101, 2893480, -3446167, -2438326, 3966343, -617709};
