/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define FULLY_CONNECTED_INT16_BIG_OUT_CH 11
#define FULLY_CONNECTED_INT16_BIG_IN_CH 7
#define FULLY_CONNECTED_INT16_BIG_INPUT_W 10
#define FULLY_CONNECTED_INT16_BIG_INPUT_H 10
#define FULLY_CONNECTED_INT16_BIG_DST_SIZE 33
#define FULLY_CONNECTED_INT16_BIG_INPUT_SIZE 700
#define FULLY_CONNECTED_INT16_BIG_OUT_ACTIVATION_MIN -1444
#define FULLY_CONNECTED_INT16_BIG_OUT_ACTIVATION_MAX 32767
#define FULLY_CONNECTED_INT16_BIG_INPUT_BATCHES 3
#define FULLY_CONNECTED_INT16_BIG_INPUT_OFFSET 0
#define FULLY_CONNECTED_INT16_BIG_OUTPUT_OFFSET 0
#define FULLY_CONNECTED_INT16_BIG_OUTPUT_MULTIPLIER 1592769218
#define FULLY_CONNECTED_INT16_BIG_OUTPUT_SHIFT -11
#define FULLY_CONNECTED_INT16_BIG_ACCUMULATION_DEPTH 700
