// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t fully_connected_int16_big_output_ref[33] = {
    -1444, 645,   -949, -1388, -1394, -1090, 973, -1291, -852,  1342,  -216,  -1326, 801,   -1064, -1380, -1370, -1248,
    1066,  -1246, -882, 1488,  -189,  -1359, 830, -1052, -1441, -1386, -1113, 1024,  -1196, -806,  1406,  -253};
