/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_0_FUNC_ALT0 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_0_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_13_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_19_FUNC_ALT0 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_19_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_1_FUNC_ALT0 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_1_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_24_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_24_FUNC_ALT1 0x01u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_24_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_25_FUNC_ALT1 0x01u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_25_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_28_FUNC_ALT0 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_28_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_2_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_2_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_2_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_3_FUNC_ALT1 0x01u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_3_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_5_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_5_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO1_2_FUNC_ALT7 0x07u

/*! @name PIO0_0 (number 36), _DBGIF_TCK_SWCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define DBGIF_TCK_SWCLK_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define DBGIF_TCK_SWCLK_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define DBGIF_TCK_SWCLK_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define DBGIF_TCK_SWCLK_PIN 0U                   /*!<@brief PORT pin number */
#define DBGIF_TCK_SWCLK_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_1 (number 2), _DBGIF_TDI
  @{ */

/* Symbols to be used with GPIO driver */
#define DBGIF_TDI_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define DBGIF_TDI_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define DBGIF_TDI_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define DBGIF_TDI_PIN 1U                   /*!<@brief PORT pin number */
#define DBGIF_TDI_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PIO0_2 (number 52), _DBGIF_TMS_SWDIO
  @{ */

/* Symbols to be used with GPIO driver */
#define DBGIF_TMS_SWDIO_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define DBGIF_TMS_SWDIO_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define DBGIF_TMS_SWDIO_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define DBGIF_TMS_SWDIO_PIN 2U                   /*!<@brief PORT pin number */
#define DBGIF_TMS_SWDIO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_28 (number 44), _DBGIF_TMS_SWDIO_TXEN
  @{ */

/* Symbols to be used with GPIO driver */
#define DBGIF_TMS_SWDIO_TXEN_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define DBGIF_TMS_SWDIO_TXEN_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define DBGIF_TMS_SWDIO_TXEN_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define DBGIF_TMS_SWDIO_TXEN_PIN 28U                   /*!<@brief PORT pin number */
#define DBGIF_TMS_SWDIO_TXEN_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_19 (number 58), _DBGIF_RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define DBGIF_RESET_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define DBGIF_RESET_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define DBGIF_RESET_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define DBGIF_RESET_PIN 19U                   /*!<@brief PORT pin number */
#define DBGIF_RESET_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PIO0_13 (number 46), _DBGIF_RESET_TXEN
  @{ */

/* Symbols to be used with GPIO driver */
#define DBGIF_RESET_TXEN_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define DBGIF_RESET_TXEN_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define DBGIF_RESET_TXEN_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define DBGIF_RESET_TXEN_PIN 13U                   /*!<@brief PORT pin number */
#define DBGIF_RESET_TXEN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_3 (number 53), _DBGIF_TDO_SWO
  @{ */
#define DBGIF_TDO_SWO_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define DBGIF_TDO_SWO_PIN 3U                   /*!<@brief PORT pin number */
#define DBGIF_TDO_SWO_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PIO0_24 (number 45), _FC0_TARGET_RXD
  @{ */
#define FC0_TARGET_RXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define FC0_TARGET_RXD_PIN 24U                   /*!<@brief PORT pin number */
#define FC0_TARGET_RXD_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_25 (number 51), _FC0_TARGET_TXD
  @{ */
#define FC0_TARGET_TXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define FC0_TARGET_TXD_PIN 25U                   /*!<@brief PORT pin number */
#define FC0_TARGET_TXD_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_5 (number 56), _LED1
  @{ */

/* Symbols to be used with GPIO driver */
#define LED1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define LED1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
#define LED1_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define LED1_PIN 5U                   /*!<@brief PORT pin number */
#define LED1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void MCU_LINK_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
