// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_3_input[18] =
    {22, -107, -85, 27, 66, -22, 35, -30, 66, -58, -51, 3, -28, -63, 45, -65, -113, -17};
