// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_3_output_ref[10] = {22, -107, 66, -22, 66, -58, -28, -63, -113, -17};
