/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_null_bias_0_input[66] = {
    -118, -10, -64, -86, 91,  -114, -29, -73, 89,  42, 22,  37,  56, 71,  45, 43,   35, 37, 48,  38,   34,  -49,
    -117, 85,  33,  -78, -90, 83,   -10, 53,  21,  39, -14, 31,  58, 28,  14, -120, 11, 54, -21, -7,   -83, 69,
    -90,  19,  39,  87,  -45, 116,  -42, -4,  -35, 4,  48,  -54, 94, -47, 23, 4,    62, 74, 39,  -121, -60, -83};
