// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_null_bias_0_output_ref[10] = {87, -35, 28, -8, 42, 102, -82, 29, -33, 99};
