/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t fully_connected_null_bias_0_weights[165] = {
    5, 3,  3, -1, 5, 2, 3,  6,  1,  3, 4, -1, 3, 3,  4,  5, 4,  0,  2, 1,  4,  1, 5, -1, 0, 2, 3, 4,  3,  5, 4, 1, 4,
    3, 6,  2, -1, 1, 3, 5,  3,  2,  5, 4, 2,  0, 2,  -1, 4, 1,  -1, 4, 1,  -1, 1, 3, 1,  6, 4, 5, 1,  2,  0, 2, 6, 4,
    2, -1, 0, 5,  1, 2, 1,  -1, -1, 3, 5, 6,  6, -1, 6,  6, 4,  2,  4, 5,  5,  4, 2, 6,  5, 6, 1, -1, 3,  3, 6, 1, 6,
    0, 4,  5, 1,  0, 4, -1, 1,  1,  5, 4, -1, 6, 5,  3,  0, -1, 1,  4, -1, 0,  5, 2, -1, 1, 4, 4, 6,  6,  0, 6, 0, 3,
    2, 6,  1, 6,  6, 6, 4,  6,  2,  2, 3, 4,  5, 1,  5,  4, -1, 5,  5, 1,  3,  1, 2, 0,  6, 0, 5, 2,  -1, 1, 5, 1, 6};
