// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define SOFTMAX_S8_S16_NUM_ROWS 2
#define SOFTMAX_S8_S16_ROW_SIZE 12
#define SOFTMAX_S8_S16_INPUT_MULT 1078071151
#define SOFTMAX_S8_S16_INPUT_LEFT_SHIFT 19
#define SOFTMAX_S8_S16_DIFF_MIN -3968
#define SOFTMAX_S8_S16_DST_SIZE 24
