// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t softmax_s8_s16_input[24] = {-44, 37, -39, 46,  20,  56, 17,  -69, -73, 25, -124, 125,
                                       17,  22, 18,  -89, 111, 67, -78, 9,   -54, 13, -36,  75};
