// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t softmax_s8_s16_output_ref[12] =
    {-28076, -26545, -25573, -28413, -26714, -26322, -28481, -25138, -28203, -28581, -29016, -26618};
