// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t softmax_s8_s16_output_ref[24] = {-28290, -26615, -28201, -26394, -27012, -26139, -27079, -28708,
                                             -28771, -26898, -29496, -24079, -27220, -27110, -27199, -29107,
                                             -24747, -26018, -28946, -27392, -28569, -27307, -28262, -25803};
