// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_input[24] = {20183, -23048, -15231, 10789,  -6367, 27963, -26106, -1231,
                                         2446,  25423,  26697,  -2364,  25704, 18452, -21040, -31483,
                                         4698,  -27687, 528,    -31263, 32596, 14781, 25349,  -17077};
