// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_3x2_dilation_input[18] =
    {9, -66, 120, -126, 118, -52, 9, -8, 120, 38, 31, -107, -36, -81, -128, -14, 105, -30};
