// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_3x2_dilation_weights[36] = {126,  100,  -112, -31, 22,  28,  28, 110, 41,  -79, 19, 104,
                                            127,  -122, 4,    -38, 16,  96,  -7, 111, 17,  34,  31, -123,
                                            -110, 99,   27,   -80, -36, 114, 12, 21,  127, -65, 38, 54};
