// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define SOFTMAX_S16_NUM_ROWS 3
#define SOFTMAX_S16_ROW_SIZE 10
#define SOFTMAX_S16_INPUT_MULT 1718013132
#define SOFTMAX_S16_INPUT_LEFT_SHIFT -2
#define SOFTMAX_S16_DST_SIZE 30
