// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t softmax_s16_input[30] = {-9644,  -28042, -8526,  29765, -5843,  -5893, -21496, 20033,  23677, 18875,
                                     -27118, -15266, 17315,  24609, 24257,  8343,  -2746,  -27513, 19950, -24181,
                                     -11068, -27257, -27051, 18595, -22234, 5207,  24933,  -27986, 31412, 28522};
