// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t softmax_s16_input[10] = {1847, 28314, -15399, -21445, 23646, -32766, 29521, -5296, -1753, -16004};
