// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t softmax_s16_output_ref[30] = {1986, 1133, 2055, 6611, 2230, 2227, 1383, 4912, 5490, 4742,
                                          1200, 1723, 4657, 5818, 5756, 3542, 2525, 1186, 5047, 1313,
                                          1856, 1133, 1140, 4590, 1320, 3051, 5570, 1108, 6787, 6214};
