// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t softmax_s16_output_ref[10] = {2920, 6547, 1725, 1434, 5678, 1015, 6793, 2347, 2616, 1693};
