// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define MUL_DST_SIZE 160
#define MUL_OUT_ACTIVATION_MIN -128
#define MUL_OUT_ACTIVATION_MAX 127
#define MUL_INPUT1_OFFSET 128
#define MUL_INPUT2_OFFSET 128
#define MUL_OUTPUT_MULT 1077952640
#define MUL_OUTPUT_SHIFT -7
#define MUL_OUTPUT_OFFSET -128
