// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t int16xint8_dilation_1_weights[16] =
    {-127, -37, 74, 1, -85, 102, -110, 65, -77, 127, 110, 124, 17, -10, 110, -110};
