// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2x3_dilation_output_ref[18] =
    {-20, -61, -16, -61, 8, -61, 72, -61, -5, -61, 34, -61, 25, -61, 13, -61, 38, -56};
