// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2x3_dilation_weights[36] = {39,  -73, 41, 20, -92,  -3,   98,  10,  126, 77,   127, 58,
                                            -89, 93,  17, 76, -105, -119, 75,  120, 116, 52,   109, -96,
                                            -35, 99,  2,  81, 22,   27,   -18, 127, 30,  -104, 17,  -31};
