// Generated by generate_test_data.py using TFL version 2.9.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_kernel_3x3_null_bias_output_mult[5] = {1864971143,
                                                               1710982645,
                                                               1086474004,
                                                               2104508734,
                                                               2070289096};
