// Generated by generate_test_data.py using TFL version 2.9.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_kernel_3x3_null_bias_output_ref[30] = {39,  17, 67, 77, 116, 70, 25, 121, 104, 53,
                                                            -58, 33, 11, 26, 42,  20, 10, 42,  127, 103,
                                                            -14, 34, 39, 78, 93,  3,  48, -20, 71,  126};
