// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_sub_block_biases[9] = {26347, 2944, -19652, 5051, 35483, -36527, 28607, 29176, -60420};
