// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_sub_block_output_shift[9] = {-10, -10, -9, -9, -9, -9, -9, -9, -10};
