// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_sub_block_output_mult[9] =
    {1827537650, 1703636848, 1812050049, 1688149247, 1781074849, 1331934207, 1858512967, 1719124448, 2075339371};
