// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_3x3_dilation_5x5_input_weights[36] = {
    -100, -7,   87,   -40, -124, -81, -8,  50,  -18, 13,  -125, -109, -114, 14, 127, 123, -24,  -79,
    51,   -118, -101, 103, -127, -74, 124, 123, -46, -47, 114,  -119, -105, 96, 10,  -84, -113, -55};
