/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#define DEPTHWISE_OUT_ACTIVATION_OUT_CH 3
#define DEPTHWISE_OUT_ACTIVATION_IN_CH 3
#define DEPTHWISE_OUT_ACTIVATION_INPUT_W 6
#define DEPTHWISE_OUT_ACTIVATION_INPUT_H 5
#define DEPTHWISE_OUT_ACTIVATION_DST_SIZE 6
#define DEPTHWISE_OUT_ACTIVATION_INPUT_SIZE 90
#define DEPTHWISE_OUT_ACTIVATION_OUT_ACTIVATION_MIN -31
#define DEPTHWISE_OUT_ACTIVATION_OUT_ACTIVATION_MAX 24
#define DEPTHWISE_OUT_ACTIVATION_INPUT_BATCHES 1
#define DEPTHWISE_OUT_ACTIVATION_INPUT_OFFSET 0
#define DEPTHWISE_OUT_ACTIVATION_OUTPUT_OFFSET 0
#define DEPTHWISE_OUT_ACTIVATION_FILTER_X 3
#define DEPTHWISE_OUT_ACTIVATION_FILTER_Y 4
#define DEPTHWISE_OUT_ACTIVATION_STRIDE_X 2
#define DEPTHWISE_OUT_ACTIVATION_STRIDE_Y 2
#define DEPTHWISE_OUT_ACTIVATION_PAD_X 0
#define DEPTHWISE_OUT_ACTIVATION_PAD_Y 0
#define DEPTHWISE_OUT_ACTIVATION_OUTPUT_W 2
#define DEPTHWISE_OUT_ACTIVATION_OUTPUT_H 1
#define DEPTHWISE_OUT_ACTIVATION_CH_MULT 1
