/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_out_activation_input[90] = {
    124, 81,   3,   -16, -85,  87,   -42, -122, 91,   3,   80,  -14,  -110, 87,  -52,  94,   -98,  -55,
    36,  -96,  -42, -5,  20,   -73,  40,  -12,  113,  -2,  66,  -68,  13,   69,  -114, -106, 63,   63,
    70,  -1,   -84, 25,  -24,  95,   73,  83,   61,   -40, 79,  114,  -48,  -69, 98,   12,   -100, -48,
    6,   -106, 91,  -92, 66,   -101, 92,  -71,  -49,  -45, -85, 80,   -35,  110, -106, -74,  17,   -60,
    -89, -91,  15,  73,  -105, 58,   94,  52,   -118, -3,  -25, -108, 0,    48,  68,   119,  -11,  45};
