// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_out_activation_output_mult[3] = {1244020336, 1173222389, 1274362280};
