/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_out_activation_weights[36] = {127, -84, 104, -112, -127, 77,  -112, -48,  66,   -123, 71, -86,
                                                   -25, 114, -5,  -13,  -1,   -6,  -87,  -109, 75,   -62,  -7, -64,
                                                   95,  -8,  -57, -17,  -95,  -71, -76,  95,   -127, 63,   71, 43};
