// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_out_activation_weights[36] = {127, -84, 104, -112, -127, 77,  -112, -48,  66,   -123, 71, -86,
                                                   -25, 114, -5,  -13,  -1,   -6,  -87,  -109, 75,   -62,  -7, -64,
                                                   95,  -8,  -57, -17,  -95,  -71, -76,  95,   -127, 63,   71, 43};
