/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#define SVDF_3_INPUT_OFFSET 0
#define SVDF_3_OUTPUT_OFFSET 0
#define SVDF_3_MULTIPLIER_IN 1347440720
#define SVDF_3_MULTIPLIER_OUT 1073741824
#define SVDF_3_SHIFT_1 -4
#define SVDF_3_SHIFT_2 1
#define SVDF_3_IN_ACTIVATION_MIN -32767
#define SVDF_3_IN_ACTIVATION_MAX 32767
#define SVDF_3_RANK 1
#define SVDF_3_FEATURE_BATCHES 12
#define SVDF_3_TIME_BATCHES 2
#define SVDF_3_INPUT_SIZE 20
#define SVDF_3_DST_SIZE 12
#define SVDF_3_OUT_ACTIVATION_MIN -128
#define SVDF_3_OUT_ACTIVATION_MAX 127
#define SVDF_3_INPUT_BATCHES 1
