/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_3_input_sequence[40] = {-51, 76, 26,  0,   -102, 26,  26,  26, 26, 76,  26,  0,   26, -51,
                                        76,  26, -51, 51,  -102, -76, -76, 0,  26, -76, -51, -26, 26, -76,
                                        -76, 76, -51, -26, 0,    -76, -76, 26, 51, -76, 51,  -76};
