// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_3_input_sequence[40] = {-64, -83, 38, 1,   119, -124, -53,  -63, 52,   -23, -22, -122, -79, -22,
                                        80,  87,  14, -3,  107, -67,  57,   -2,  -104, 97,  62,  -26,  101, -126,
                                        -53, 10,  23, -32, 28,  -68,  -108, 100, -8,   117, -72, -26};
