// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_3_output_ref[12] = {20, 74, 56, 65, -23, 57, -49, -128, 2, 109, 72, -13};
