// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t svdf_3_weights_time[24] = {-17,  -93, -78, -65,  46,   109, -70, -68, -41, -47, 2,   -108,
                                       -108, -42, 69,  -103, -127, 73,  100, 113, -52, 98,  -74, -14};
