// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int64_t fully_connected_int16_biases[11] =
    {-1411210, 2069961, -3545380, -1414388, -4053207, -3264892, -938857, 583225, 761105, -3288542, 3302019};
