/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.5.0 as reference.
#pragma once
#include <stdint.h>

const q15_t fully_connected_int16_input[126] = {
    -3,  -38, 24,  8,   -11, -43, 47,  45,  6,   -10, -3,  -52, -23, 9,   32,  3,   -7,  -2,  -5,  28, -40,
    -21, -39, 6,   -45, 35,  -8,  -16, -16, 2,   -9,  -42, -35, 12,  -37, 33,  14,  -47, -32, -38, 40, 13,
    12,  46,  12,  -46, 27,  -42, 33,  3,   -43, 53,  3,   -50, -35, 27,  -3,  -18, 12,  -39, -47, 28, 1,
    30,  8,   -50, 11,  -23, 1,   4,   -31, 17,  2,   -35, -20, 51,  -32, -42, -37, -37, 36,  -12, 38, -12,
    -28, -46, -49, -56, 17,  -32, 6,   -19, -47, 5,   -17, -29, 1,   50,  -39, 1,   39,  8,   -19, 56, 5,
    -44, -28, -49, -36, 23,  51,  -7,  -10, 15,  53,  50,  -15, -52, -52, -1,  -46, 50,  -52, -49, 38, 9};
