// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t fully_connected_int16_output_ref[22] = {-835,  -7347, -1676, -4901, -962,  2602,  -1572, -2171,
                                                    -628,  8714,  703,   18336, 16905, 11770, -9999, 2312,
                                                    -9999, -9999, 14275, 12875, -9999, -4643};
