// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_dilation_golden_input[48] = {91,  10,   63,  -51, -30, 96,  22,  125,  -87, -100, -86, 62,
                                             -78, -108, -84, -20, -51, 40,  123, 116,  114, 27,   -79, 6,
                                             -98, 11,   115, 104, -41, 104, -97, 100,  -18, -48,  70,  -29,
                                             -49, -90,  -48, 109, 81,  24,  -8,  -116, 23,  117,  80,  -4};
