// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t conv_dilation_golden_output_mult[3] = {1525243435, 1321877636, 1685030762};
