// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_dilation_golden_weights[12] = {127, -60, -71, -28, 43, -38, 127, 71, 123, 127, -99, 83};
