// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_null_bias_1_output_mult[8] =
    {1493638723, 1161718960, 1963858195, 1618108556, 1535128667, 1714918530, 1742578493, 1175548942};
