// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_null_bias_1_output_mult[16] = {1644376469,
                                                       1419504469,
                                                       1222741455,
                                                       1560049509,
                                                       1588158496,
                                                       1489777042,
                                                       1475722549,
                                                       1686540056,
                                                       1082196522,
                                                       1517886029,
                                                       1630321976,
                                                       1433558962,
                                                       1770867016,
                                                       1700594549,
                                                       1644376469,
                                                       1728703536};
