// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_null_bias_1_output_shift[16] =
    {-9, -9, -9, -9, -9, -10, -9, -9, -9, -9, -9, -9, -9, -9, -9, -9};
