// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_null_bias_1_weights[32] = {-127, 127, 120, -127, -49,  -119, 74,   127,  62,  56,  127,
                                                -53,  97,  -47, -45,  -103, -32,  95,   -64,  99,  114, 66,
                                                -127, -67, -72, -71,  70,   115,  -127, -127, -58, 43};
