// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define MUL_S16_DST_SIZE 160
#define MUL_S16_OUT_ACTIVATION_MIN -32768
#define MUL_S16_OUT_ACTIVATION_MAX 32767
#define MUL_S16_INPUT1_OFFSET 0
#define MUL_S16_INPUT2_OFFSET 0
#define MUL_S16_OUTPUT_MULT 1073774592
#define MUL_S16_OUTPUT_SHIFT -14
#define MUL_S16_OUTPUT_OFFSET 0
