// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define CONV_4_OUT_CH 3
#define CONV_4_IN_CH 3
#define CONV_4_INPUT_W 5
#define CONV_4_INPUT_H 5
#define CONV_4_DST_SIZE 36
#define CONV_4_INPUT_SIZE 75
#define CONV_4_OUT_ACTIVATION_MIN -109
#define CONV_4_OUT_ACTIVATION_MAX 127
#define CONV_4_INPUT_BATCHES 3
#define CONV_4_FILTER_X 2
#define CONV_4_FILTER_Y 3
#define CONV_4_STRIDE_X 2
#define CONV_4_STRIDE_Y 2
#define CONV_4_PAD_X 0
#define CONV_4_PAD_Y 0
#define CONV_4_OUTPUT_W 2
#define CONV_4_OUTPUT_H 2
#define CONV_4_INPUT_OFFSET 128
#define CONV_4_OUTPUT_OFFSET 70
#define CONV_4_DILATION_X 1
#define CONV_4_DILATION_Y 1
