/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_4_weights[54] = {-127, -23, 88,   -26, 14,   39,  -79, -53,  -94, -97,  105,  17,  -119, 115,
                                 74,   81,  44,   59,  -117, 118, 70,  59,   -26, -126, -101, -30, 127,  -1,
                                 103,  58,  -85,  -92, -73,  -72, -81, -115, 16,  -13,  -76,  95,  -19,  -105,
                                 -81,  14,  -104, 59,  13,   14,  30,  -110, 11,  -68,  -82,  127};
