Basic math functions
Basic math functions
Neural Network Functions
Functions
arm_cmsis_nn_status arm_elementwise_add_s16 (const int16_t *input_1_vect, const int16_t *input_2_vect, const int32_t input_1_offset, const int32_t input_1_mult, const int32_t input_1_shift, const int32_t input_2_offset, const int32_t input_2_mult, const int32_t input_2_shift, const int32_t left_shift, int16_t *output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
s16 elementwise add of two vectors
arm_cmsis_nn_status arm_elementwise_add_s8 (const int8_t *input_1_vect, const int8_t *input_2_vect, const int32_t input_1_offset, const int32_t input_1_mult, const int32_t input_1_shift, const int32_t input_2_offset, const int32_t input_2_mult, const int32_t input_2_shift, const int32_t left_shift, int8_t *output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
s8 elementwise add of two vectors
arm_cmsis_nn_status arm_elementwise_mul_s16 (const int16_t *input_1_vect, const int16_t *input_2_vect, const int32_t input_1_offset, const int32_t input_2_offset, int16_t *output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
s16 element wise multiplication of two vectors
arm_cmsis_nn_status arm_elementwise_mul_s8 (const int8_t *input_1_vect, const int8_t *input_2_vect, const int32_t input_1_offset, const int32_t input_2_offset, int8_t *output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
s8 element wise multiplication of two vectors
Description
Elementwise add and multiplication functions.
Function Documentation
arm_cmsis_nn_status arm_elementwise_add_s16 (const int16_t * input_1_vect, const int16_t * input_2_vect, const int32_t input_1_offset, const int32_t input_1_mult, const int32_t input_1_shift, const int32_t input_2_offset, const int32_t input_2_mult, const int32_t input_2_shift, const int32_t left_shift, int16_t * output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
Parameters
[in] input_1_vect pointer to input vector 1
[in] input_2_vect pointer to input vector 2
[in] input_1_offset offset for input 1. Not used.
[in] input_1_mult multiplier for input 1
[in] input_1_shift shift for input 1
[in] input_2_offset offset for input 2. Not used.
[in] input_2_mult multiplier for input 2
[in] input_2_shift shift for input 2
[in] left_shift input left shift
[in,out] output pointer to output vector
[in] out_offset output offset. Not used.
[in] out_mult output multiplier
[in] out_shift output shift
[in] out_activation_min minimum value to clamp output to. Min: -32768
[in] out_activation_max maximum value to clamp output to. Max: 32767
[in] block_size number of samples
Returns
The function returns ARM_CMSIS_NN_SUCCESS
References ARM_CMSIS_NN_SUCCESS, arm_nn_read_q15x2_ia(), arm_nn_requantize(), arm_nn_write_q15x2_ia(), MAX, MIN, and PACK_Q15x2_32x1.
arm_cmsis_nn_status arm_elementwise_add_s8 (const int8_t * input_1_vect, const int8_t * input_2_vect, const int32_t input_1_offset, const int32_t input_1_mult, const int32_t input_1_shift, const int32_t input_2_offset, const int32_t input_2_mult, const int32_t input_2_shift, const int32_t left_shift, int8_t * output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
Parameters
[in] input_1_vect pointer to input vector 1
[in] input_2_vect pointer to input vector 2
[in] input_1_offset offset for input 1. Range: -127 to 128
[in] input_1_mult multiplier for input 1
[in] input_1_shift shift for input 1
[in] input_2_offset offset for input 2. Range: -127 to 128
[in] input_2_mult multiplier for input 2
[in] input_2_shift shift for input 2
[in] left_shift input left shift
[in,out] output pointer to output vector
[in] out_offset output offset. Range: -128 to 127
[in] out_mult output multiplier
[in] out_shift output shift
[in] out_activation_min minimum value to clamp output to. Min: -128
[in] out_activation_max maximum value to clamp output to. Max: 127
[in] block_size number of samples
Returns
The function returns ARM_CMSIS_NN_SUCCESS
References ARM_CMSIS_NN_SUCCESS, arm_nn_requantize(), arm_nn_write_q7x4_ia(), MAX, MIN, and PACK_Q7x4_32x1.
arm_cmsis_nn_status arm_elementwise_mul_s16 (const int16_t * input_1_vect, const int16_t * input_2_vect, const int32_t input_1_offset, const int32_t input_2_offset, int16_t * output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
s16 elementwise multiplication
Note
Refer header file for details.
References ARM_CMSIS_NN_SUCCESS, arm_nn_read_q15x2_ia(), arm_nn_requantize(), arm_nn_write_q15x2_ia(), MAX, MIN, and PACK_Q15x2_32x1.
arm_cmsis_nn_status arm_elementwise_mul_s8 (const int8_t * input_1_vect, const int8_t * input_2_vect, const int32_t input_1_offset, const int32_t input_2_offset, int8_t * output, const int32_t out_offset, const int32_t out_mult, const int32_t out_shift, const int32_t out_activation_min, const int32_t out_activation_max, const int32_t block_size)
s8 elementwise multiplication
Note
Refer header file for details.
References ARM_CMSIS_NN_SUCCESS, arm_nn_requantize(), arm_nn_write_q7x4_ia(), MAX, MIN, and PACK_Q7x4_32x1.