name: CoreValidation
on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - .github/workflows/corevalidation.yml
      - CMSIS/Core/**/*
      - CMSIS/Core_A/**/*
      - CMSIS/CoreValidation/**/*
      - Device/ARM/**/*
  workflow_dispatch:

# The env variables relate to an ARM AWS account for CMSIS_5
# If you are forking CMSIS_5 repo, please use your own info.
env:
  AWS_ASSUME_ROLE: arn:aws:iam::720528183931:role/Proj-vht-assume-role
  AWS_DEFAULT_REGION: eu-west-1
  AWS_IAM_PROFILE: Proj-vht-limited-actions
  AWS_S3_BUCKET_NAME: gh-cmsis-5
  AWS_SECURITY_GROUP_ID: sg-03afe5ec007b4bcb0
  AWS_SUBNET_ID: subnet-025b7baebd743a68b
jobs:
  ci_test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      avhresult: ${{ steps.avh.conclusion }}
      testbadge: ${{ steps.avh.outputs.badge }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install AVH Client for Python
      run: |
        pip install git+https://github.com/ARM-software/avhclient.git@v0.1

    - uses: ammaraskar/gcc-problem-matcher@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Run tests
      id: avh
      run: |
        avhclient -b aws execute --specfile CMSIS/CoreValidation/Project/avh.yml

    - name: Archive build results
      uses: actions/upload-artifact@v3
      with:
        name: builds
        path: CMSIS/CoreValidation/Project/Core_Validation-*.zip
        retention-days: 1
        if-no-files-found: error
      if: always()

    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: tests
        path: CMSIS/CoreValidation/Project/Core_Validation-*.junit
        retention-days: 1
        if-no-files-found: error
      if: always()

    - name: Archive event file
      uses: actions/upload-artifact@v3
      with:
        name: EventFile
        path: ${{ github.event_path }}
