name: Build documentation and pack
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: github.event_name == 'release'
        run: |
          git fetch --tags --force

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.6
          packchk-version: 1.3.98
          gen-doc-script: ./CMSIS/DoxyGen/gen_doc.sh
          check-links-script: ./CMSIS/DoxyGen/check_links.sh
          doc-path: ./CMSIS/Documentation/
          gen-pack-script: ./gen_pack.sh --no-preprocess
          gen-pack-output: ./output
          gh-pages-branch: gh-pages
