// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_mult4_biases[8] =
    {223178, -4314998, 3439509, 1837855, -3006016, 2312206, -2798955, -2952197};
