// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_mult4_output_ref[8] = {14964, 113, 4445, -17539, -15735, 3848, -3806, 14080};
