// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_eq_in_out_ch_biases[6] = {11638, 15523, 23835, 6771, 24700, -31756};
