/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_eq_in_out_ch_input[120] = {
    74,   -116, -83, 2,    59,   39, -46, 96,   34,   -79,  81,   -99, 13,  88,  66,  67,  -63, -20, -87,  -100,
    -60,  115,  -21, -117, -31,  85, -76, 85,   25,   25,   -105, 109, 65,  -6,  -57, 7,   -2,  81,  106,  -87,
    108,  -124, 5,   10,   16,   17, -31, 106,  -47,  -26,  -93,  -67, 59,  99,  -88, -72, 0,   -19, -108, 92,
    -127, 55,   72,  90,   -121, -9, 0,   -31,  -110, -108, 51,   -9,  92,  15,  77,  82,  -38, 10,  125,  112,
    -93,  -47,  62,  98,   58,   -1, 15,  -123, 112,  0,    94,   71,  72,  22,  102, -33, -62, 67,  64,   -70,
    -88,  79,   -65, -116, -100, 21, -38, -16,  13,   24,   18,   108, -44, -68, 85,  -44, 62,  -5,  -96,  78};
