/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_eq_in_out_ch_output_ref[120] = {
    -23, 112, 50,  -20, 44,  -53, -35, 111, 6,   -25, 20,  -7,  -35, 59,  -27, -15, 58,  -86, -8,  28,
    -2,  -43, 21,  -7,  7,   53,  25,  -11, -20, -44, -13, 71,  -6,  5,   36,  -53, -19, 76,  -20, -44,
    -7,  -7,  -4,  30,  20,  5,   17,  -57, -64, 42,  -27, -19, -9,  -66, -60, 59,  13,  -30, 14,  -40,
    -72, 62,  -19, 1,   51,  -56, -15, 34,  5,   -6,  3,   -63, -55, 78,  -50, -8,  37,  -41, -53, 50,
    24,  13,  44,  -70, -86, 73,  30,  -4,  5,   -83, -14, 32,  -31, -26, -24, -32, 19,  -6,  24,  -3,
    10,  -86, 5,   42,  28,  -25, -18, -81, -18, 16,  13,  -42, -29, -37, 38,  31,  27,  4,   11,  -81};
