/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.4.1 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_eq_in_out_ch_output_ref[120] = {
    -1, -4, -4, -2, -1, -3, -6, -2, 1,  -1, 0,  0,  1,  -5, -5, 6, -3, 3,  -4, -3, -4, 2, -5, -1,
    -2, -2, 0,  5,  -1, -2, -3, 1,  -2, 3,  2,  5,  -7, -3, -4, 4, 3,  1,  0,  -4, -2, 0, 2,  -6,
    -2, -2, -4, 4,  -4, -4, -2, 1,  -3, 6,  -1, 7,  -1, -2, -1, 8, -2, -1, -2, -4, -3, 5, -1, -6,
    0,  -4, -4, 5,  -7, 0,  -5, -4, -4, -3, -3, -1, 3,  0,  -7, 6, -1, -8, -2, -2, -1, 6, -7, -3,
    1,  1,  -5, 7,  -2, 1,  2,  0,  -6, 9,  0,  -1, -6, -2, 1,  4, -2, -8, -1, 0,  -2, 2, 1,  -2};
