// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int32_t depthwise_eq_in_out_ch_output_mult[6] =
    {1964839021, 1857386938, 1918788128, 1688533548, 1811335929, 1581081349};
