// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_eq_in_out_ch_weights[36] = {47,   13, 45,   44,  -57,  -51, -11,  -98, -109, -51, -89, -76,
                                                 -2,   10, -88,  -80, -127, -92, -127, 127, 65,   -59, 100, 127,
                                                 -115, 12, -127, -99, 25,   123, -81,  86,  27,   127, 27,  -85};
