// Generated by generate_test_data.py using TFL version 2.9.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_eq_in_out_ch_weights[36] = {-127, 26,   -11, -74,  -11, 78,  104,  127,  114, 3,    -75, 127,
                                                 -92,  9,    0,   -114, 127, -28, -102, -121, 46,  -124, 100, 86,
                                                 -113, -125, 83,  127,  -87, -78, -27,  51,   127, -52,  -60, 74};
