/*
 * Copyright (C) 2010-2021 Arm Limited or its affiliates.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_eq_in_out_ch_weights[36] = {47,   13, 45,   44,  -57,  -51, -11,  -98, -109, -51, -89, -76,
                                                 -2,   10, -88,  -80, -127, -92, -127, 127, 65,   -59, 100, 127,
                                                 -115, 12, -127, -99, 25,   123, -81,  86,  27,   127, 27,  -85};
